### ISSUE TITLE
Twitter sentiment graph buggy?

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectF#369]
I saw that this happens only on the website provided by you, not on csv.got.show. Basically:

When I open up the page I get the graph with a certain zoom, thus some labels on top of the graph like "season XYZ". If then I zoom around, the original labels stay and some more labels are produced that move according to zoom or navigation (Screenshot attached, notice that "season 05" between season 03 and season 04)

![screen shot 2016-04-10 at 3 06 47 pm](https://cloud.githubusercontent.com/assets/6240943/14410368/26985b76-ff2e-11e5-8e6d-dadb83d977a8.png)

It happens both on the character page as well as on the homepage, you might want to look at the https://beta.got.show (now with consistent, curated tweets and sentiment analysis)

**Comment by yashha** [comment]
Top tags are now fixed but the tags at the bottom have still this issue.

**Comment by marcusnovotny** [comment]
Can you share the code? I'm like 100% sure you're creating two graphs on top of each other.

You can see the second scroll bar on the right
![](http://i.imgur.com/iEjjOQq.png)

**Comment by sacdallago** [comment]
That might also be the reason for #396

**Comment by sacdallago** [comment]
@marcusnovotny I have proven your thesis:
What I get inspecting csv.got.show:
![abc](https://cloud.githubusercontent.com/assets/6240943/14487416/a9734052-0162-11e6-964a-a497d08a49cb.jpg)

while on the got.show:

![cba](https://cloud.githubusercontent.com/assets/6240943/14487424/b5347ece-0162-11e6-9ec6-1c8af982f1b0.jpg)

The first time I checked, there were even **three** `g` elements. One you delete one of the `g` elements and have the svg with just one, it works like charm

**Comment by sacdallago** [comment]
Great fix for the home. Can this be ported to the characters page? the problem still persists there

**Comment by yashha** [comment]
Oh sure :)
Does it fix the bug with the macs?
